apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-demo-app
  template:
    metadata:
      labels:
        app: k8s-demo-app
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: k8s-demo-app
        image: k8sdemoregistrynov2021.azurecr.io/k8s/demo:latest
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-demo-app
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: k8s-demo-app