name: Build Push Deploy Docker Image

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: k8s/demo
  RG_NAME: k8s-demo-rg
  AKSCLUSTER_NAME: k8s-demo-kubernetes

jobs:
  build-and-push:
    name: "Build and Push to ACR"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      #Build the Image
      - name: Build Docker Image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"

      #Login to the Container Registry
      - name: Log in to Azure Container Registry
        run: echo "${{ secrets.ACR_APPPASSWORD }}" | docker login ${{ secrets.ACR_URL }} --username ${{ secrets.ACR_APPID }} --password-stdin

      # Tag and Push the Image to the Registry
      - name: Push image to Azure Container Registry
        run: |
          IMAGE_ID=${{ secrets.ACR_URL }}/$IMAGE_NAME
          VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

  deploy-to-k8s:
    needs: build-and-push
    name: "Deploy to Kubernetes"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      #Login to Azure CLI
      - name: Login to Azure CLI
        run: az login --service-principal -u ${{ secrets.ACR_APPID }} -p ${{ secrets.ACR_APPPASSWORD }} --tenant ${{ secrets.APP_TENANTID }}

      #Get and Store the AKS Credentials
      - name: Get AKS Login Credentials
        run: az aks get-credentials --resource-group $RG_NAME --name $AKSCLUSTER_NAME

      - name: Test Kubernetes Access
        run: kubectl get nodes
