name: Build Push Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      #Build the Image
      - name: Test kubectl version
        run: kubectl version